input_folder: /vols/cms/ks1021/offline/HiggsDNA/master/HiggsDNA/productions/ZPT_POWHEG
output_path: /vols/cms/ks1021/TIDAL/Draw/Figures/deriving_zpt_reweighting/POWHEG/validation/NLO
channels: [ mm ]
eras: [ Run3_2022 ]
# parameter_path: /vols/cms/ks1021/offline/HiggsDNA/master/HiggsDNA/scripts/ditau/config/
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/master/HiggsDNA/scripts/ditau/config/NLO/
schemes: [ zpt_control ]

variables:
  zpt_control:
    definitions:
      m_vis: "m_vis(75,50,200)"
      pt_vis: "pt_vis[0,10,20,30,40,60,80,100,120,160,200,280,320,400,600]"
      eta_1: "eta_1(30,-3,3)"
      eta_2: "eta_2(30,-3,3)"
      n_jets: "n_jets(4,0,4)"
      pt_1: "pt_1(40,0,200)"
      pt_2: "pt_2(40,0,200)"
      mt_1: "mt_1(40,0,300)"
      mt_2: "mt_2(40,0,300)"
      mjj: "mjj(40,0,2000)"
      met_pt: "met_pt(40,0,200)"

    mm:
    - [ "1", inclusive, m_vis ]
    - [ "1", inclusive, pt_vis ]
    # - [ "1", inclusive, eta_1 ]
    # - [ "1", inclusive, eta_2 ]
    # - [ "1", inclusive, n_jets ]
    # - [ "1", inclusive, pt_1 ]
    # - [ "1", inclusive, pt_2 ]
    # - [ "1", inclusive, mt_1 ]
    # - [ "1", inclusive, mt_2 ]
    # - [ "1", inclusive, mjj ]
    # - [ "1", inclusive, met_pt ]

    ee:
    - [ "1", inclusive, m_vis ]
    - [ "1", inclusive, pt_vis ]

  zpt_calculation:
    definitions:
      pt_vis: "pt_vis[0,10,20,30,40,60,80,100,120,160,200,250,300,600]"
    additional_selections:
      mvis_50to60: "m_vis > 50 && m_vis < 60"
      mvis_60to70: "m_vis > 60 && m_vis < 70"
      mvis_70to80: "m_vis > 70 && m_vis < 80"
      mvis_80to90: "m_vis > 80 && m_vis < 90"
      mvis_90to100: "m_vis > 90 && m_vis < 100"
      mvis_100to120: "m_vis > 100 && m_vis < 120"
      mvis_120to140: "m_vis > 120 && m_vis < 140"
      mvis_140to160: "m_vis > 140 && m_vis < 160"
      mvis_160to180: "m_vis > 160 && m_vis < 180"
      mvis_180to200: "m_vis > 180 && m_vis < 200"
      mvis_200to300: "m_vis > 200 && m_vis < 300"
      mvis_300to400: "m_vis > 300 && m_vis < 400"
      mvis_400to600: "m_vis > 400 && m_vis < 600"
      mvis_600to800: "m_vis > 600 && m_vis < 800"
      mvis_800toinf: "m_vis > 800"

    mm:
    - [ "1", inclusive, pt_vis ]
