input_folder: /vols/cms/ks1021/offline/HiggsDNA/IC/IP_corrections/before_2/
output_path: /vols/cms/ks1021/TIDAL/Draw/plots/IP_corrections/before_2/
channels: [mm]
eras: [Run3_2022]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/IC/scripts/ditau/config/
schemes: [ip_calculation]

variables:
  ip_calculation:
    definitions:
      ip_x_1: "ip_x_1(300,-0.03,0.03)"
      ip_x_2: "ip_x_2(300,-0.03,0.03)"
      ip_y_1: "ip_y_1(300,-0.03,0.03)"
      ip_y_2: "ip_y_2(300,-0.03,0.03)"
      ip_z_1: "ip_z_1(300,-0.03,0.03)"
      ip_z_2: "ip_z_2(300,-0.03,0.03)"
      # ip_x_1: "ip_x_1(200,-0.02,0.02)"
      # ip_x_2: "ip_x_2(200,-0.02,0.02)"
      # ip_y_1: "ip_y_1(200,-0.02,0.02)"
      # ip_y_2: "ip_y_2(200,-0.02,0.02)"
      # ip_z_1: "ip_z_1(200,-0.02,0.02)"
      # ip_z_2: "ip_z_2(200,-0.02,0.02)"
      ip_LengthSig_1: "ip_LengthSig_1[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,10.0]"
      ip_LengthSig_2: "ip_LengthSig_2[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,10.0]"
      ip_LengthTotal_1: "ip_LengthTotal_1(200,0,0.1)"
      ip_LengthTotal_2: "ip_LengthTotal_2(200,0,0.1)"
      ip_ErrorTotal_1: "ip_ErrorTotal_1(200,0,0.05)"
      ip_ErrorTotal_2: "ip_ErrorTotal_2(200,0,0.05)"
      log_err00_1: "log_err00_1(200, -3.5, -2)"
      log_err00_2: "log_err00_2(200, -3.5, -2)"
      log_err11_1: "log_err11_1(200, -3.5, -2)"
      log_err11_2: "log_err11_2(200, -3.5, -2)"
      log_err22_1: "log_err22_1(200, -3.5, -2)"
      log_err22_2: "log_err22_2(200, -3.5, -2)"
      ip_alt_LengthSig_1: "ip_alt_LengthSig_1(200,0,10)"
      ip_alt_LengthSig_2: "ip_alt_LengthSig_2(200,0,10)"
      ip_x_1_Err: "ip_x_1_Err(1000,0,0.1)"
      ip_x_2_Err: "ip_y_1_Err(1000,0,0.1)"
      ip_y_1_Err: "ip_z_1_Err(1000,0,0.1)"
      ip_y_2_Err: "ip_x_2_Err(1000,0,0.1)"
      ip_z_1_Err: "ip_y_2_Err(1000,0,0.1)"
      ip_z_2_Err: "ip_z_2_Err(1000,0,0.1)"
      ip_x_1_log_Err: "ip_x_1_log_Err(500, -4, -1)"
      ip_x_2_log_Err: "ip_x_2_log_Err(500, -4, -1)"
      ip_y_1_log_Err: "ip_y_1_log_Err(500, -4, -1)"
      ip_y_2_log_Err: "ip_y_2_log_Err(500, -4, -1)"
      ip_z_1_log_Err: "ip_z_1_log_Err(500, -4, -1)"
      ip_z_2_log_Err: "ip_z_2_log_Err(500, -4, -1)"
      ip_x_1_Err_ratio: "ip_x_1_Err_ratio(200, -10, 10)"
      ip_x_2_Err_ratio: "ip_x_2_Err_ratio(200, -10, 10)"
      ip_y_1_Err_ratio: "ip_y_1_Err_ratio(200, -10, 10)"
      ip_y_2_Err_ratio: "ip_y_2_Err_ratio(200, -10, 10)"
      ip_z_1_Err_ratio: "ip_z_1_Err_ratio(200, -10, 10)"
      ip_z_2_Err_ratio: "ip_z_2_Err_ratio(200, -10, 10)"
      ip_cov00_1: "ip_cov00_1(100,0.0,0.001)"
      ip_cov00_2: "ip_cov00_2(100,0.0,0.001)"
      ip_cov11_1: "ip_cov11_1(100,0.0,0.001)"
      ip_cov11_2: "ip_cov11_2(100,0.0,0.001)"
      ip_cov22_1: "ip_cov22_1(100,0.0,0.001)"
      ip_cov22_2: "ip_cov22_2(100,0.0,0.001)"
      ip_cov10_1: "ip_cov10_1(1000,-0.000075,0.000075)"
      ip_cov10_2: "ip_cov10_2(1000,-0.000075,0.000075)"
      ip_cov20_1: "ip_cov20_1(1000,-0.000025,0.000025)"
      ip_cov20_2: "ip_cov20_2(1000,-0.000025,0.000025)"
      ip_cov21_1: "ip_cov21_1(1000,-0.000025,0.000025)"
      ip_cov21_2: "ip_cov21_2(1000,-0.000025,0.000025)"
      PCA_ip_cov00_1_mm: "PCA_ip_cov00_1(1000,1.5e-7,2e-5)"
      PCA_ip_cov00_2_mm: "PCA_ip_cov00_2(1000,1.5e-7,2e-5)"
      PCA_ip_cov11_1_mm: "PCA_ip_cov11_1(1000,-0.8e-5,0.5e-5)"
      PCA_ip_cov11_2_mm: "PCA_ip_cov11_2(1000,-0.8e-5,0.5e-5)"
      PCA_ip_cov22_1_mm: "PCA_ip_cov22_1(1000,-4e-19,4e-19)"
      PCA_ip_cov22_2_mm: "PCA_ip_cov22_2(1000,-4e-19,4e-19)"
      PCA_ip_cov10_1_mm: "PCA_ip_cov10_1(1000,-6.2e-6,0.6e-5)"
      PCA_ip_cov10_2_mm: "PCA_ip_cov10_2(1000,-6.2e-6,0.6e-5)"
      PCA_ip_cov20_1_mm: "PCA_ip_cov20_1(1000,-0.7e-18,1.2e-18)"
      PCA_ip_cov20_2_mm: "PCA_ip_cov20_2(1000,-0.7e-18,1.2e-18)"
      PCA_ip_cov21_1_mm: "PCA_ip_cov21_1(1000,-3e-19,3e-19)"
      PCA_ip_cov21_2_mm: "PCA_ip_cov21_2(1000,-3e-19,3e-19)"
      PCA_ip_cov00_1_ee: "PCA_ip_cov00_1(1000,7.3e-7,6e-5)"
      PCA_ip_cov00_2_ee: "PCA_ip_cov00_2(1000,7.3e-7,6e-5)"
      PCA_ip_cov11_1_ee: "PCA_ip_cov11_1(1000,-1e-5,1e-5)"
      PCA_ip_cov11_2_ee: "PCA_ip_cov11_2(1000,-3.5e-6,3.5e-6)"
      PCA_ip_cov22_1_ee: "PCA_ip_cov22_1(1000,-3e-21,3e-21)"
      PCA_ip_cov22_2_ee: "PCA_ip_cov22_2(1000,-3e-21,3e-21)"
      PCA_ip_cov10_1_ee: "PCA_ip_cov10_1(1000,-2e-5,2e-5)"
      PCA_ip_cov10_2_ee: "PCA_ip_cov10_2(1000,-2e-5,2e-5)"
      PCA_ip_cov20_1_ee: "PCA_ip_cov20_1(1000,-1.5e-20,1.5e-20)"
      PCA_ip_cov20_2_ee: "PCA_ip_cov20_2(1000,-1.5e-20,1.5e-20)"
      PCA_ip_cov21_1_ee: "PCA_ip_cov21_1(1000,-1.5e-21,1.5e-21)"
      PCA_ip_cov21_2_ee: "PCA_ip_cov21_2(1000,-1.5e-21,1.5e-21)"

    additional_selections:
      mm:
        eta_1_0p0to0p9: "eta_1 > 0.0 && eta_1 < 0.9"
        eta_1_0p9to1p2: "eta_1 > 0.9 && eta_1 < 1.2"
        eta_1_1p2to2p1: "eta_1 > 1.2 && eta_1 < 2.1"
        eta_1_2p1to2p4: "eta_1 > 2.1"
        eta_2_0p0to0p9: "eta_2 > 0.0 && eta_2 < 0.9"
        eta_2_0p9to1p2: "eta_2 > 0.9 && eta_2 < 1.2"
        eta_2_1p2to2p1: "eta_2 > 1.2 && eta_2 < 2.1"
        eta_2_2p1to2p4: "eta_2 > 2.1"
      ee:
        eta_1_0p0to1p0: "eta_1 > 0.0 && eta_1 < 1.0"
        eta_1_1p0to1p48: "eta_1 > 1.0 && eta_1 < 1.48"
        eta_1_1p48to1p65: "eta_1 > 1.48 && eta_1 < 1.65"
        eta_1_1p65to2p1: "eta_1 > 1.65 && eta_1 < 2.1"
        eta_2_0p0to1p0: "eta_2 > 0.0 && eta_2 < 1.0"
        eta_2_1p0to1p48: "eta_2 > 1.0 && eta_2 < 1.48"
        eta_2_1p48to1p65: "eta_2 > 1.48 && eta_2 < 1.65"
        eta_2_1p65to2p1: "eta_2 > 1.65 && eta_2 < 2.1"

    mm:
      - ["1", inclusive, ip_x_1]
      - ["1", inclusive, ip_x_2]
      - ["1", inclusive, ip_y_1]
      - ["1", inclusive, ip_y_2]
      - ["1", inclusive, ip_z_1]
      - ["1", inclusive, ip_z_2]
      - ["1", inclusive, log_err00_1]
      - ["1", inclusive, log_err00_2]
      - ["1", inclusive, log_err11_1]
      - ["1", inclusive, log_err11_2]
      - ["1", inclusive, log_err22_1]
      - ["1", inclusive, log_err22_2]
      - ["1", inclusive, ip_LengthSig_1]
      - ["1", inclusive, ip_LengthSig_2]
      - ["1", inclusive, ip_LengthTotal_1]
      - ["1", inclusive, ip_LengthTotal_2]
      - ["1", inclusive, ip_ErrorTotal_1]
      - ["1", inclusive, ip_ErrorTotal_2]
      #- ["1", inclusive, ip_alt_LengthSig_1]
      #- ["1", inclusive, ip_alt_LengthSig_2]
      #- ["1", inclusive, ip_x_1_Err_ratio]
      #- ["1", inclusive, ip_x_2_Err_ratio]
      #- ["1", inclusive, ip_y_1_Err_ratio]
      #- ["1", inclusive, ip_y_2_Err_ratio]
      #- ["1", inclusive, ip_z_1_Err_ratio]
      #- ["1", inclusive, ip_z_2_Err_ratio]
      #- ["1", inclusive, ip_LengthTotal_1]
      #- ["1", inclusive, ip_LengthTotal_2]
      #- ["1", inclusive, ip_ErrorTotal_1]
      #- ["1", inclusive, ip_ErrorTotal_2]

    ee:
      - ["1", inclusive, ip_x_1]
      - ["1", inclusive, ip_x_2]
      - ["1", inclusive, ip_y_1]
      - ["1", inclusive, ip_y_2]
      - ["1", inclusive, ip_z_1]
      - ["1", inclusive, ip_z_2]
      - ["1", inclusive, ip_LengthSig_1]
      - ["1", inclusive, ip_LengthSig_2]
      - ["1", inclusive, ip_LengthTotal_1]
      - ["1", inclusive, ip_LengthTotal_2]
      - ["1", inclusive, ip_ErrorTotal_1]
      - ["1", inclusive, ip_ErrorTotal_2]
      - ["1", inclusive, PCA_ip_cov00_1_ee]
      - ["1", inclusive, PCA_ip_cov00_2_ee]
      - ["1", inclusive, PCA_ip_cov11_1_ee]
      - ["1", inclusive, PCA_ip_cov11_2_ee]
      - ["1", inclusive, PCA_ip_cov22_1_ee]
      - ["1", inclusive, PCA_ip_cov22_2_ee]
      - ["1", inclusive, PCA_ip_cov10_1_ee]
      - ["1", inclusive, PCA_ip_cov10_2_ee]
      - ["1", inclusive, PCA_ip_cov20_1_ee]
      - ["1", inclusive, PCA_ip_cov20_2_ee]
      - ["1", inclusive, PCA_ip_cov21_1_ee]
      - ["1", inclusive, PCA_ip_cov21_2_ee]