input_folder: /vols/cms/ks1021/offline/HiggsDNA/IC/outputs/production_11_11_2024
output_path: /vols/cms/ks1021/TIDAL/Draw/plots/production_11_11_2024/
channels: [ee,mm]
eras: [Run3_2022]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/IC/scripts/ditau/config/
schemes: [ip_control,ip_calculation]

variables:
  ip_control:
    definitions:
      m_vis: "m_vis(40,0,200)"
      pt_vis: "pt_vis[0,10,20,30,40,60,80,100,120,160,200,280,320,400,600]"
      eta_1: "eta_1(30,-3,3)"
      eta_2: "eta_2(30,-3,3)"
      pt_1: "pt_1(40,0,200)"
      pt_2: "pt_2(40,0,200)"
      met_phi: "met_phi(20,-3.14,3.14)"
      met_pt: "met_pt(40,0,200)"

      ip_x_1: "ip_x_1(100,-0.01,0.01)"
      ip_x_2: "ip_x_2(100,-0.01,0.01)"
      ip_y_1: "ip_y_1(100,-0.01,0.01)"
      ip_y_2: "ip_y_2(100,-0.01,0.01)"
      ip_z_1: "ip_z_1(100,-0.01,0.01)"
      ip_z_2: "ip_z_2(100,-0.01,0.01)"
      ip_LengthSig_1: "ip_LengthSig_1(100,0,10)"
      ip_LengthSig_2: "ip_LengthSig_2(100,0,10)"
      ip_x_1_Err: "ip_x_1_Err(100,0,0.1)"
      ip_x_2_Err: "ip_y_1_Err(100,0,0.1)"
      ip_y_1_Err: "ip_z_1_Err(100,0,0.1)"
      ip_y_2_Err: "ip_x_2_Err(100,0,0.1)"
      ip_z_1_Err: "ip_y_2_Err(100,0,0.1)"
      ip_z_2_Err: "ip_z_2_Err(100,0,0.1)"

    mm:
      - ["1", inclusive, m_vis]
      - ["1", inclusive, pt_vis]
      - ["1", inclusive, eta_1]
      - ["1", inclusive, eta_2]
      - ["1", inclusive, pt_1]
      - ["1", inclusive, pt_2]
      - ["1", inclusive, met_phi]
      - ["1", inclusive, met_pt]
      - ["1", inclusive, ip_x_1]
      - ["1", inclusive, ip_x_2]
      - ["1", inclusive, ip_y_1]
      - ["1", inclusive, ip_y_2]
      - ["1", inclusive, ip_z_1]
      - ["1", inclusive, ip_z_2]
      - ["1", inclusive, ip_LengthSig_1]
      - ["1", inclusive, ip_LengthSig_2]
      - ["1", inclusive, ip_x_1_Err]
      - ["1", inclusive, ip_x_2_Err]
      - ["1", inclusive, ip_y_1_Err]
      - ["1", inclusive, ip_y_2_Err]
      - ["1", inclusive, ip_z_1_Err]
      - ["1", inclusive, ip_z_2_Err]
    ee:
      - ["1", inclusive, m_vis]
      - ["1", inclusive, pt_vis]
      - ["1", inclusive, eta_1]
      - ["1", inclusive, eta_2]
      - ["1", inclusive, pt_1]
      - ["1", inclusive, pt_2]
      - ["1", inclusive, met_phi]
      - ["1", inclusive, met_pt]
      - ["1", inclusive, ip_x_1]
      - ["1", inclusive, ip_x_2]
      - ["1", inclusive, ip_y_1]
      - ["1", inclusive, ip_y_2]
      - ["1", inclusive, ip_z_1]
      - ["1", inclusive, ip_z_2]
      - ["1", inclusive, ip_LengthSig_1]
      - ["1", inclusive, ip_LengthSig_2]
      - ["1", inclusive, ip_x_1_Err]
      - ["1", inclusive, ip_x_2_Err]
      - ["1", inclusive, ip_y_1_Err]
      - ["1", inclusive, ip_y_2_Err]
      - ["1", inclusive, ip_z_1_Err]
      - ["1", inclusive, ip_z_2_Err]

  ip_calculation:
    definitions:
      ip_x_1: "ip_x_1(100,-0.01,0.01)"
      ip_x_2: "ip_x_2(100,-0.01,0.01)"
      ip_y_1: "ip_y_1(100,-0.01,0.01)"
      ip_y_2: "ip_y_2(100,-0.01,0.01)"
      ip_z_1: "ip_z_1(100,-0.01,0.01)"
      ip_z_2: "ip_z_2(100,-0.01,0.01)"
      ip_LengthSig_1: "ip_LengthSig_1(100,0,10)"
      ip_LengthSig_2: "ip_LengthSig_2(100,0,10)"
      ip_x_1_Err: "ip_x_1_Err(100,0,0.1)"
      ip_x_2_Err: "ip_y_1_Err(100,0,0.1)"
      ip_y_1_Err: "ip_z_1_Err(100,0,0.1)"
      ip_y_2_Err: "ip_x_2_Err(100,0,0.1)"
      ip_z_1_Err: "ip_y_2_Err(100,0,0.1)"
      ip_z_2_Err: "ip_z_2_Err(100,0,0.1)"

    additional_selections:
      mm:
        eta_1_0p0to0p9: "eta_1 > 0.0 && eta_1 < 0.9"
        eta_1_0p9to1p2: "eta_1 > 0.9 && eta_1 < 1.2"
        eta_1_1p2to2p1: "eta_1 > 1.2 && eta_1 < 2.1"
        eta_1_2p1to2p4: "eta_1 > 2.1"
        eta_2_0p0to0p9: "eta_2 > 0.0 && eta_2 < 0.9"
        eta_2_0p9to1p2: "eta_2 > 0.9 && eta_2 < 1.2"
        eta_2_1p2to2p1: "eta_2 > 1.2 && eta_2 < 2.1"
        eta_2_2p1to2p4: "eta_2 > 2.1"
      ee:
        eta_1_0p0to1p0: "eta_1 > 0.0 && eta_1 < 1.0"
        eta_1_1p0to1p48: "eta_1 > 1.0 && eta_1 < 1.48"
        eta_1_1p48to1p65: "eta_1 > 1.48 && eta_1 < 1.65"
        eta_1_1p65to2p1: "eta_1 > 1.65 && eta_1 < 2.1"
        eta_2_0p0to1p0: "eta_2 > 0.0 && eta_2 < 1.0"
        eta_2_1p0to1p48: "eta_2 > 1.0 && eta_2 < 1.48"
        eta_2_1p48to1p65: "eta_2 > 1.48 && eta_2 < 1.65"
        eta_2_1p65to2p1: "eta_2 > 1.65 && eta_2 < 2.1"

    mm:
      - ["1", inclusive, ip_x_1]
      - ["1", inclusive, ip_x_2]
      - ["1", inclusive, ip_y_1]
      - ["1", inclusive, ip_y_2]
      - ["1", inclusive, ip_z_1]
      - ["1", inclusive, ip_z_2]
      - ["1", inclusive, ip_LengthSig_1]
      - ["1", inclusive, ip_LengthSig_2]
      - ["1", inclusive, ip_x_1_Err]
      - ["1", inclusive, ip_x_2_Err]
      - ["1", inclusive, ip_y_1_Err]
      - ["1", inclusive, ip_y_2_Err]
      - ["1", inclusive, ip_z_1_Err]
      - ["1", inclusive, ip_z_2_Err]
    ee:
      - ["1", inclusive, ip_x_1]
      - ["1", inclusive, ip_x_2]
      - ["1", inclusive, ip_y_1]
      - ["1", inclusive, ip_y_2]
      - ["1", inclusive, ip_z_1]
      - ["1", inclusive, ip_z_2]
      - ["1", inclusive, ip_LengthSig_1]
      - ["1", inclusive, ip_LengthSig_2]
      - ["1", inclusive, ip_x_1_Err]
      - ["1", inclusive, ip_x_2_Err]
      - ["1", inclusive, ip_y_1_Err]
      - ["1", inclusive, ip_y_2_Err]
      - ["1", inclusive, ip_z_1_Err]
      - ["1", inclusive, ip_z_2_Err]
