input_folder: /vols/cms/ks1021/offline/HiggsDNA/IC/output/production
output_path: /vols/cms/ks1021/TIDAL/Draw/plots
channels: [mt]
eras: [Run3_2022]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/IC/scripts/ditau/config/
schemes: [control]

variables:
  control:
    definitions:
      m_vis: "m_vis(50,0,400)"
      pt_1: "pt_1(40,0,200)"
      pt_2: "pt_2(40,0,200)"
      alphaAngle_mu_pi_1: "alphaAngle_mu_pi_1[0.0,0.08,0.16,0.24,0.32,0.4,0.48,0.56,0.64,0.72,0.8,0.88,0.96,1.04,1.12,1.2,1.28,1.36,1.44,1.52,1.6]"
      aco_mu_pi: "aco_mu_pi(20,0,2pi)"
      ip_x_1: "ip_x_1(50,-0.01,0.01)"
      ip_y_1: "ip_y_1(50,-0.01,0.01)"
      ip_z_1: "ip_z_1(50,-0.01,0.01)"
      ip_x_2: "ip_x_2(50,-0.01,0.01)"
      ip_y_2: "ip_y_2(50,-0.01,0.01)"
      ip_z_2: "ip_z_2(50,-0.01,0.01)"
      decayMode_2: "decayMode_2[0,1,2,3,4,5,6,7,8,9,10,11,12]"
      decayModePNet_2: "decayModePNet_2[0,1,2,3,4,5,6,7,8,9,10,11,12]"

    tt:
      - ["3", inclusive, m_vis]
      - ["3", inclusive, pt_1]
      - ["3", inclusive, pt_2]
    mt:
      - ["2", inclusive, m_vis]
      - ["2", inclusive, pt_1]
      - ["2", inclusive, pt_2]
      - ["2", inclusive, alphaAngle_mu_pi_1]
      - ["1", aminus_low, aco_mu_pi]
      - ["1", aminus_high, aco_mu_pi]
      - ["2", inclusive, ip_x_1]
      - ["2", inclusive, ip_y_1]
      - ["2", inclusive, ip_z_1]
      - ["2", inclusive, ip_x_2]
      - ["2", inclusive, ip_y_2]
      - ["2", inclusive, ip_z_2]
      - ["2", inclusive, decayMode_2]
      - ["2", inclusive, decayModePNet_2]
