input_folder: /vols/cms/lcr119/offline/HiggsCP/HiggsDNA/output/fullsyst_ThesisUnblinding_rerun
output_path: /vols/cms/lcr119/offline/HiggsCP/TIDAL/Draw/Plots/Control/Sep09
channels: [tt]
eras: [Run3_2022, Run3_2022EE, Run3_2023, Run3_2023BPix]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/IC/scripts/ditau/config/
schemes: [control]

control:
  variable_definitions:
    # CONTROL PLOTS
    m_vis: "m_vis(50,0,200)"
    m_vis_tt: "m_vis(50,0,400)"
    pt_1: "pt_1(40,0,200)"
    pt_2: "pt_2(40,0,200)"
    eta_1: "eta_1(21,-2.1,2.1)"
    eta_2: "eta_2(21,-2.1,2.1)"
    phi_1: "phi_1(32,-pi,pi)"
    phi_2: "phi_2(32,-pi,pi)"
    dR: "dR(42,0,5)"
    n_jets: "n_jets(10,0,10)"
    met_pt: "met_pt(40,0,200)"
    pt_tt: "pt_tt(50,0,400)"
    met_phi: "met_phi(32,-pi,pi)"

  mt:
  # GENERAL CONTROL
  - { method: "5", category:  [ cp_inclusive ], plotting_variable: [ m_vis, pt_tt, pt_1, pt_2, eta_1, eta_2, phi_1, phi_2, dR, n_jets, met_pt], additional_selections: ["(mt_1<65)"]}

  et:
  # GENERAL CONTROL
  - { method: "5", category:  [ cp_inclusive ], plotting_variable: [ m_vis, pt_tt, pt_1, pt_2, eta_1, eta_2, phi_1, phi_2, dR, n_jets, met_pt], additional_selections: ["(mt_1<65)"]}

  tt:
  # GENERAL CONTROL
  - { method: "4", category:  [ cp_inclusive ], plotting_variable: [ m_vis_tt, pt_tt, pt_1, pt_2, eta_1, eta_2, phi_1, phi_2, dR, n_jets, met_pt ]}
  # - { method: "4", category:  [ cp_inclusive ], plotting_variable: [ m_vis_tt,  n_jets], additional_selections: [ "(1)" ], same_sign: True}
  # - { method: "4", category:  [ cp_inclusive ], plotting_variable: [ m_vis_tt,  n_jets], additional_selections: [ "(1)" ], aiso: True}

  mm:
  # GENERAL CONTROL
  - { method: "5", category:  [ inclusive ], plotting_variable: [ m_vis, met_pt]}


