input_folder: /vols/cms/ks1021/offline/HiggsDNA/IC/output/v1
output_path: /vols/cms/ks1021/TIDAL/Draw/plots
channels: [tt]
eras: [Run3_2022]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/IC/scripts/ditau/config/
schemes: [control]

variables:
  control:
    definitions:
      m_vis: "m_vis(15,50,200)"
      pt_1: "pt_1(10,0,100)"
      pt_2: "pt_2(10,0,100)"
    tt:
      - ["3", inclusive, m_vis]
      - ["3", inclusive, pt_1]
      - ["3", inclusive, pt_2]