input_folder: /vols/cms/ia2318/HiggsDNA/output/production_070525_EarlyRun3SyncMSSM/
output_path: /vols/cms/ia2318/TIDAL/Draw/production_070525_EarlyRun3SyncMSSM_blind
channels: [mt,tt]
eras: [Run3_2022EE]
parameter_path: /vols/cms/ia2318/HiggsDNA/scripts/ditau/config/
schemes: [control]

working_points:
  et:
    vsJet: "Medium"
    vsEle: "Tight"
    vsMu: "VLoose"
  mt:
    vsJet: "Medium"
    vsEle: "VVLoose"
    vsMu: "Tight"
  tt:
    vsJet: "Medium"
    vsEle: "VVLoose"
    vsMu: "VLoose"

variables:
  control:
    definitions:
      m_vis: "m_vis(50,0,400)"
      pt_1: "pt_1(40,0,200)"
      pt_2: "pt_2(40,0,200)"
      eta_1: "eta_1(40,-pi,pi)"
      eta_2: "eta_2(40,-pi,pi)"
      phi_1: "phi_1(40,-pi,pi)"
      phi_2: "phi_2(40,-pi,pi)"
      decayMode_1: "decayMode_1[0,1,2,3,4,5,6,7,8,9,10,11,12]"
      decayMode_2: "decayMode_2[0,1,2,3,4,5,6,7,8,9,10,11,12]"
      mt_tot_btag: "mt_tot[0,60,80,100,120,140,160,180,200,250,300,350,400,500,600,700,800,900,1100,1300,1500,1700,1900,2100,2300,2500,2700,2900,3100,3300,3500,3700,3900,4100,4300,4500,4700,5000]" 
      mt_tot_nobtag: "mt_tot[0,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,225,250,275,300,325,350,400,450,500,600,700,800,900,1100,1300,1500,1700,1900,2100,2300,2500,2700,2900,3100,3300,3500,3700,3900,4100,4300,4500,4700,5000]"
      ## check binning in old code https://github.com/danielwinterbottom/ICHiggsTauTau/blob/efaf3bc6283772d1c4903f12407b4367495d6670/Analysis/HiggsTauTauRun2/scripts/makeDatacards_mssm_combined.py#L115
      # https://github.com/danielwinterbottom/ICHiggsTauTau/blob/efaf3bc6283772d1c4903f12407b4367495d6670/Analysis/HiggsTauTauRun2/scripts/makeDatacards_mssm_combined.py#L291
      # re-optimise mTLt40 once set-up is finalised for semileptonic analysis
      # bliding for mt_tot -- ## need to automate it for submitting iteratively as well
      FastMTT_mass: "FastMTT_mass(150,0,500)"

    tt:
      - ["3", inclusive, m_vis]
      - ["3", inclusive, pt_1]
      - ["3", inclusive, pt_2]
      - ["3", inclusive, eta_1]
      - ["3", inclusive, eta_2]
      - ["3", inclusive, phi_1]
      - ["3", inclusive, phi_2]
      - ["3", inclusive, mt_tot_nobtag, blind]
      - ["3", inclusive, FastMTT_mass]
      - ["3", nobtag, m_vis]
      - ["3", nobtag, pt_1]
      - ["3", nobtag, pt_2]
      - ["3", nobtag, eta_1]
      - ["3", nobtag, eta_2]
      - ["3", nobtag, phi_1]
      - ["3", nobtag, phi_2]
      - ["3", nobtag, mt_tot_nobtag, blind]
      - ["3", nobtag, FastMTT_mass]
      - ["3", btag, m_vis]
      - ["3", btag, pt_1]
      - ["3", btag, pt_2]
      - ["3", btag, eta_1]
      - ["3", btag, eta_2]
      - ["3", btag, phi_1]
      - ["3", btag, phi_2]
      - ["3", btag, mt_tot_btag, blind]
      - ["3", btag, FastMTT_mass]
    mt:
      - ["1", inclusive, m_vis]
      - ["1", inclusive, pt_1]
      - ["1", inclusive, pt_2]
      - ['1', inclusive, eta_1]
      - ['1', inclusive, eta_2]
      - ['1', inclusive, phi_1]
      - ['1', inclusive, phi_2]
      - ["1", inclusive, mt_tot_nobtag, blind]
      - ["1", inclusive, FastMTT_mass]
      - ["1", nobtag, m_vis]
      - ["1", nobtag, pt_1]
      - ["1", nobtag, pt_2]
      - ['1', nobtag, eta_1]
      - ['1', nobtag, eta_2]
      - ['1', nobtag, phi_1]
      - ['1', nobtag, phi_2]
      - ["1", nobtag, mt_tot_nobtag, blind]
      - ["1", nobtag, FastMTT_mass]
      - ["1", btag, m_vis]
      - ["1", btag, pt_1]
      - ["1", btag, pt_2]
      - ['1', btag, eta_1]
      - ['1', btag, eta_2]
      - ['1', btag, phi_1]
      - ['1', btag, phi_2]
      - ["1", btag, mt_tot_btag, blind]
      - ["1", btag, FastMTT_mass]
    et:  # confirm with Danny what Method to use for  et (cannot use 2 with mTLt40) cat -- give mt_1 < 40 GeV selection not in name but later
    # use -sel option functionality in makeDatacards_mssm.py
      - ["2", inclusive, m_vis]
      - ["2", inclusive, pt_1]
      - ["2", inclusive, pt_2]
      - ['2', inclusive, eta_1]
      - ['2', inclusive, eta_2]
      - ['2', inclusive, phi_1]
      - ['2', inclusive, phi_2]
      - ["2", inclusive, mt_tot_nobtag, blind]
      - ["2", inclusive, FastMTT_mass]
      - ["2", nobtag, m_vis]
      - ["2", nobtag, pt_1]
      - ["2", nobtag, pt_2]
      - ['2', nobtag, eta_1]
      - ['2', nobtag, eta_2]
      - ['2', nobtag, phi_1]
      - ['2', nobtag, phi_2]
      - ["2", nobtag, mt_tot_nobtag, blind]
      - ["2", nobtag, FastMTT_mass]
      - ["2", btag, m_vis]
      - ["2", btag, pt_1]
      - ["2", btag, pt_2]
      - ['2', btag, eta_1]
      - ['2', btag, eta_2]
      - ['2', btag, phi_1]
      - ['2', btag, phi_2]
      - ["2", btag, mt_tot_btag, blind]
      - ["2", btag, FastMTT_mass]
