input_folder: /vols/cms/ks1021/offline/HiggsDNA/master/HiggsDNA/productions/POWHEG_TauID_apply_26_06_2025 #_derive_22_06_2025 #
output_path: /vols/cms/ks1021/TIDAL/Draw/Figures/POWHEG_TauID_apply_26_06_2025
channels: [ tt ]
eras: [ Run3_2022 ]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/master/HiggsDNA/scripts/ditau/config/
schemes: [ control ]
run_systematics: false

sf_calculation:
  variable_definitions:
    pt_2_vs_mvis: "pt_2,m_vis(36,20,200),(60,40,200)"
    pt_2: "pt_2(20,40,200)"
    m_vis: "m_vis(60,40,200)"
    jpt_1: "jpt_1(20,30,200)"
    jpt_2: "jpt_2(20,30,200)"

  systematics:
    per_era:
      default:
        mt:
        - [ "systematic_Tau_EnergyScale_JSCALE", "CMS_scale_jfake" ]
        - [ "systematic_Tau_EnergyScale_TSCALE", "CMS_scale_t_*group_*year" ]
        - [ "systematic_Tau_EnergyScale_MUSCALE", "CMS_scale_mu_*group_*year" ]
        - [ "systematic_QCD_Background", "CMS_QCD_BackgroundSubtraction" ]
        - [ "systematic_Jet_EnergyScale_Total", "CMS_scale_j_*year" ]
        - [ "systematic_Jet_EnergyResolution", "CMS_res_j_*year" ]
        common:
        - [ "systematic_DY_Shape_Imperial", "CMS_htt_dyShape" ]
        - [ "systematic_TTbar_Shape", "CMS_htt_ttbarShape" ]

  Aliases:
    Alias1: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && pt_1 > 26 && idDeepTau2018v2p5VSe_2 >= 2)"
    Alias2: "category:({category} && m_vis > 40 && pt_1 > 26 && fabs(eta_1) < 2.4 && trg_singlemuon)"
    Alias1b: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && pt_1 > 26 && idDeepTau2018v2p5VSe_2 >= 6)"

  mt:
  # remove _cp and DM2 if normal SFs
  - { method: "5", category: [ inclusive, DM0_tau_cp, DM1_tau_cp, DM2_tau_cp, DM10_tau_cp, DM11_tau_cp ], plotting_variable: [ pt_2_vs_mvis ], blind: false, auto_rebin: false, additional_selections: [ "(mt_1<65)", "(mt_1>70)" ], set_alias: Alias1, additional_weight: "(1)", unroll: false }
  - { method: "1", category: [ inclusive, DM0_tau_cp, DM1_tau_cp, DM2_tau_cp, DM10_tau_cp, DM11_tau_cp ], plotting_variable: [ pt_2_vs_mvis ], blind: false, auto_rebin: false, additional_selections: [ "(mt_1<65)" ], set_alias: Alias1, additional_weight: "(1)", aiso: True, unroll: false }

  mm:
  - { method: "1", category: [ inclusive ], plotting_variable: [ m_vis ], blind: false, auto_rebin: false, set_alias: Alias2, additional_weight: "(1)", rename_procs: true }

control:
  variable_definitions:
    m_vis: "m_vis(80,0,200)"
    m_vis_tt: "m_vis(50,0,400)"
    pt_vis: "pt_vis[0,10,20,30,40,60,80,100,120,160,200,280,320,400,600]"
    mt_1: "mt_1(100,0,300)"
    pt_1: "pt_1(50,0,200)"
    pt_tt: "pt_tt(80,0,400)"
    pt_2: "pt_2(50,0,200)"
    eta_1: "eta_1(21,-2.1,2.1)"
    eta_2: "eta_2(21,-2.1,2.1)"
    phi_1: "phi_1(32,-pi,pi)"
    phi_2: "phi_2(32,-pi,pi)"
    dR: "dR(42,0,5)"
    n_jets: "n_jets(10,0,10)"
    met_pt: "met_pt(40,0,200)"

  systematics:
    per_era:
      default:
        mt:
        - [ "systematic_Tau_EnergyScale_JSCALE", "CMS_scale_jfake" ]
        - [ "systematic_Tau_EnergyScale_TSCALE", "CMS_scale_t_*group_*year" ]
        - [ "systematic_Tau_EnergyScale_MUSCALE", "CMS_scale_mu_*group_*year" ]
        - [ "systematic_QCD_Background", "CMS_QCD_BackgroundSubtraction" ]
        - [ "systematic_Jet_EnergyScale_Total", "CMS_scale_j_*year" ]
        - [ "systematic_Jet_EnergyResolution", "CMS_res_j_*year" ]
        common:
        - [ "systematic_DY_Shape", "CMS_htt_dyShape" ]
        - [ "systematic_TTbar_Shape", "CMS_htt_ttbarShape" ]

  Aliases:
    Alias1: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && pt_1 > 26 && idDeepTau2018v2p5VSe_2 >= 2)"

  mm:
  - { method: "1", category: [ inclusive ], plotting_variable: [ m_vis, pt_vis ], blind: false, auto_rebin: false, additional_weight: "(1)", rename_procs: False }
  mt:
  - { method: "2", category: [ inclusive, cp_inclusive ], plotting_variable: [ m_vis ], blind: false, auto_rebin: false, set_alias: Alias1 }
  tt:
  - { method: "3", category: [ inclusive, cp_inclusive ], plotting_variable: [ m_vis_tt ], blind: false, auto_rebin: false, additional_selections: "(1)" }
