input_folder: /vols/cms/ks1021/offline/HiggsDNA/IC/outputs/random_test_11/
output_path: /vols/cms/ks1021/TIDAL/Draw/plots/random_test_16_VsEle_Tight/
channels: [ mt ]
eras: [ Run3_2023, Run3_2023BPix ]
parameter_path: /vols/cms/ks1021/offline/HiggsDNA/IC/scripts/ditau/config/
schemes: [ sf_calculation ]
run_systematics: true

sf_calculation:
  variable_definitions:
    #pt_2_vs_mvis_2: "pt_2,m_vis[20,25,30,35,40,50,60,80,100,200],(30,40,200)"
    pt_2_vs_mvis: "pt_2,m_vis(60,20,200),(60,40,200)"
    pt_2: "pt_2(20,40,200)"
    m_vis: "m_vis(20,50,150)"
    jpt_1: "jpt_1(20,30,200)"
    jpt_2: "jpt_2(20,30,200)"

  systematics:
    per_era:
      default:
        mt:
        - [ "systematic_Tau_EnergyScale_JSCALE", "CMS_scale_jfake" ]
        - [ "systematic_Tau_EnergyScale_TSCALE", "CMS_scale_t_*group_*year" ]
        - [ "systematic_Tau_EnergyScale_MUSCALE", "CMS_scale_mu_*group_*year" ]
        - [ "systematic_QCD_Background", "CMS_QCD_BackgroundSubtraction" ]
        - [ "systematic_Jet_EnergyScale_Total", "CMS_scale_j_*year" ]
        - [ "systematic_Jet_EnergyResolution", "CMS_res_j_*year" ]
        common:
        - [ "systematic_DY_Shape", "CMS_htt_dyShape" ]
        - [ "systematic_TTbar_Shape", "CMS_htt_ttbarShape" ]

  Aliases:
    Alias1: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && idDeepTau2018v2p5VSe_2 >= 2)"
    Alias2: "category:({category} && m_vis > 50 && pt_1 > 26 && fabs(eta_1) < 2.4 && trg_singlemuon)"
    Alias1b: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && idDeepTau2018v2p5VSe_2 >= 6)"

  mt:
  - { method: "4", category: [ inclusive, dm0, dm1, dm2, dm10, dm11 ], plotting_variable: [ pt_2_vs_mvis ], blind: false, auto_rebin: false, additional_selections: [ "(mt_1<65)", "(mt_1>70)" ], set_alias: Alias1b, additional_weight: "(1)", unroll: False }
  - { method: "1", category: [ inclusive, dm0, dm1, dm2, dm10, dm11 ], plotting_variable: [ pt_2_vs_mvis ], blind: false, auto_rebin: false, additional_selections: [ "(mt_1<65)" ], set_alias: Alias1b, additional_weight: "(1)", aiso: True, unroll: False }

  mm:
  - { method: "1", category: [ inclusive ], plotting_variable: [ m_vis ], blind: false, auto_rebin: false, set_alias: Alias2, additional_weight: "(1)", rename_procs: True }
