input_folder:  /vols/cms/lcr119/offline/HiggsCP/HiggsDNA/output/SF_templates_HPS
output_path: /vols/cms/lcr119/offline/HiggsCP/TIDAL/Draw/SF_Templates_HPS_CONTROL/CONTROL_v2p1
channels: [ mt]
eras: [ Run3_2022, Run3_2022EE, Run3_2023, Run3_2023BPix]
parameter_path: /vols/cms/lcr119/offline/HiggsCP/HiggsDNA/scripts/ditau/config/
schemes: [ sf_calculation ]
run_systematics: true

sf_calculation:
  variable_definitions:
    pt_2_vs_mvis: "pt_2,m_vis(36,20,200),(64,40,200)"
    jpt_1: "jpt_1(20,30,200)"
    jpt_2: "jpt_2(20,30,200)"

  systematics: # WARNING: For this to work, changes to the systematics code are liekly needed...
    per_era:
      default:
        mt:
        - [ "systematic_Tau_EnergyScale_JSCALE", "CMS_scale_jfake" ]
        - [ "systematic_Tau_EnergyScale_TSCALE", "CMS_scale_t_*group_*year" ]
        - [ "systematic_Tau_EnergyScale_MUSCALE", "CMS_scale_mu_*group_*year" ]
        - [ "systematic_QCD_Background", "CMS_QCD_BackgroundSubtraction" ]
        - [ "systematic_Jet_EnergyScale_Total", "CMS_scale_j_*year" ]
        - [ "systematic_Jet_EnergyResolution", "CMS_res_j_*year" ]
        common:
        - [ "systematic_DY_Shape", "CMS_htt_dyShape" ]
        - [ "systematic_TTbar_Shape", "CMS_htt_ttbarShape" ]

  Aliases:
    Alias1: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && pt_1 > 26 && idDeepTau2018v2p5VSe_2 >= 2)"
    Alias2: "category:({category} && m_vis > 40 && pt_1 > 26 && fabs(eta_1) < 2.4 && trg_singlemuon)"
    Alias1b: "category:({category} && m_vis > 40 && fabs(eta_1) < 2.4 && trg_singlemuon && pt_1 > 26 && idDeepTau2018v2p5VSe_2 >= 6)"

  mt:
  # remove _cp and DM2 if normal SFs
  - { method: "5", category: [ inclusive, DM0_tau, DM1_tau, DM10_tau, DM11_tau ], plotting_variable: [ pt_2_vs_mvis ], blind: false, auto_rebin: false, additional_selections: [ "(mt_1<65)", "(mt_1>70)" ], set_alias: Alias1b, additional_weight: "(1)", unroll: false }
  # - { method: "1", category: [ cp_inclusive, DM0_tau_cp, DM1_tau_cp, DM2_tau_cp, DM10_tau_cp, DM11_tau_cp ], plotting_variable: [ pt_2_vs_mvis ], blind: false, auto_rebin: false, additional_selections: [ "(mt_1<65)" ], set_alias: Alias1, additional_weight: "(1)", aiso: True, unroll: false }

  mm:
  - { method: "1", category: [ inclusive ], plotting_variable: [ m_vis ], blind: false, auto_rebin: false, set_alias: Alias2, additional_weight: "(1)", rename_procs: true }
